config/routes.rb
RtfBeta::Application.routes.draw do
  match 'logout' => 'sessions#destroy'
  match 'login' => 'sessions#new'
  match 'register' => 'users#create'
  match 'signup' => 'users#new'
  match 'fetch' => 'messages#fetch'

  resources :users
  resources :channels do
    resources :messages
  end
  resources :messages
  resource :session

  root :to => 'init#index'

  

end

app/views/layouts/_flashes.html.haml
#flash
  -flash.each do |key, value|
    %div{:class => key}
      = value

app/views/layouts/_user.html.haml
%ul
  %li= user_name
  %li= link_to image_tag("cog_edit.png"), '/users/edit'
  %li= link_to "Logout", logout_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title rtf
    %link{:rel => 'StyleSheet', :type => 'text/css', :href => 'stylesheets/reset.css'}
    %link{:rel => 'StyleSheet', :type => 'text/css', :href => 'stylesheets/chromatron/style.css'}
    %link{:rel => 'StyleSheet', :type => 'text/css', :href => 'stylesheets/chromatron/colors.css'}
    %link{:rel => 'StyleSheet', :type => 'text/css', :href => 'stylesheets/app.css'}
    %script{:src => '/framework/push.js'}
    = javascript_include_tag "application"
    -#%script{:src => 'javascripts/json2.js'}
    -#%script{:src => 'javascripts/underscore.js'}
    -#%script{:src => 'javascripts/handlebars.js'}
    -#%script{:src => 'javascripts/jquery.js'}
    -#%script{:src => 'javascripts/backbone.js'}
    -#%script{:src => 'javascripts/pubsub.js'}
    -#%script{:src => 'javascripts/rtf.js'}
    %script#message-template{:type => 'text/x-handlebars-template'}
      .user {{name}}
      .timestamp {{created_at}}
      .text {{{message}}}
    %script#user-template{:type => 'text/x-handlebars-template'}
      %a{:href => '#{{name}}', :class => '{{status}}'} {{name}}
      {{#if unread}}
      %span {{unread}}
      {{/if}}
    %script#user-list-template{:type => 'text/x-handlebars-template'}
      %h2 {{title}}
      %ul
    %script#current-user-template{:type => 'text/x-handlebars-template'}
      %img{:src => "{{avatar_url}}"}
      %div
        %a{:href => "#"} {{name}}
        %ul
          %li
            %a.button-link{:href => '/logout'} logout
    %script#app-template{:type => 'text/x-handlebars-template'}
      #messagewrapper
        #messagecolumn
          #messages.innertube
          #input.innertube
      #usercolumn
        {{{currentUser}}}
        {{{userList}}}
      .clearfix
    :javascript
      jQuery(function() {
        window.App = new RTF({name: "#{current_user.login}", token: "#{form_authenticity_token}"});
        App.init();
      });

  %body
    #pagewrapper
      -#
        #messagewrapper
          #messagecolumn
            #messages.innertube
              .message
                .user krunk
                .timestamp 3:59
                .text and I'm out
            #input.innertube
              %div
                %input#txt-box{:type => 'text', :placeholder => 'Type message'}
        #usercolumn
          .userinfo
            Name
        .tooltips